remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Club de Ciberseguridad
description: Club de Ciberseguridad del CIC
